# Inserts a blank line between shell prompts
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[[battery.display]]
threshold = 25

[cmd_duration]
# disabled = true
min_time = 500
# format = "ï™ [$duration](bold yellow) "
format = "[$duration](bold yellow) "

[directory]
read_only = " ğŸ”’"
truncation_length = 3
truncation_symbol = "â€¦/"

